name: MidaBuild
on: [push, workflow_dispatch] # أضفت خاصية التشغيل اليدوي أيضاً

jobs:
  mida_job:
    runs-on: windows-latest
    steps:
      - name: Fix Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # هذا السطر يضمن سحب كل الملفات بعمق كامل لحل خطأ 128

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Libs
        run: |
          python -m pip install --upgrade pip
          pip install flask flask-socketio pyautogui opencv-python numpy pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --windowed --name "Mida_Pro_x64" main.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Mida_Product
          path: dist/*.exe
          
